"""
Liste des codes juridiques francais utilises pour l'extraction de references.
"""

CODES_LOI = [
    "Code de l'action sociale et des familles",
    "Code de l'artisanat",
    "Code des assurances",
    "Code de l'aviation civile",
    "Code du cinéma et de l'image animée",
    "Code civil",
    "Code de la commande publique",
    "Code de commerce",
    "Code des communes",
    "Code des communes de la Nouvelle-Calédonie",
    "Code de la consommation",
    "Code de la construction et de l'habitation",
    "Code de la défense",
    "Code de déontologie des architectes",
    "Code disciplinaire et pénal de la marine marchande",
    "Code du domaine de l'Etat",
    "Code du domaine de l'Etat et des collectivités publiques applicable à la collectivité territoriale de Mayotte",
    "Code du domaine public fluvial et de la navigation intérieure",
    "Code des douanes",
    "Code des douanes de Mayotte",
    "Code de l'éducation",
    "Code électoral",
    "Code de l'énergie",
    "Code de l'entrée et du séjour des étrangers et du droit d'asile",
    "Code de l'environnement",
    "Code de l'expropriation pour cause d'utilité publique",
    "Code de la famille et de l'aide sociale",
    "Code forestier (nouveau)",
    "Code général de la fonction publique",
    "Code général de la propriété des personnes publiques",
    "Code général des collectivités territoriales",
    "Code général des impôts",
    "Code général des impôts, annexe I",
    "Code général des impôts, annexe II",
    "Code général des impôts, annexe III",
    "Code général des impôts, annexe IV",
    "Code des impositions sur les biens et services",
    "Code des instruments monétaires et des médailles",
    "Code des juridictions financières",
    "Code de justice administrative",
    "Code de justice militaire (nouveau)",
    "Code de la justice pénale des mineurs",
    "Code de la Légion d'honneur, de la Médaille militaire et de l'ordre national du Mérite",
    "Code minier",
    "Code minier (nouveau)",
    "Code monétaire et financier",
    "Code de la mutualité",
    "Code de l'organisation judiciaire",
    "Code du patrimoine",
    "Code pénal",
    "Code pénitentiaire",
    "Code des pensions civiles et militaires de retraite",
    "Code des pensions de retraite des marins français du commerce, de pêche ou de plaisance",
    "Code des pensions militaires d'invalidité et des victimes de guerre",
    "Code des ports maritimes",
    "Code des postes et des communications électroniques",
    "Code de procédure civile",
    "Code de procédure pénale",
    "Code des procédures civiles d'exécution",
    "Code de la propriété intellectuelle",
    "Code de la recherche",
    "Code des relations entre le public et l'administration",
    "Code de la route",
    "Code rural (ancien)",
    "Code rural et de la pêche maritime",
    "Code de la santé publique",
    "Code de la sécurité intérieure",
    "Code de la sécurité sociale",
    "Code du service national",
    "Code du sport",
    "Code du tourisme",
    "Code des transports",
    "Code du travail",
    "Code du travail maritime",
    "Code de l'urbanisme",
    "Code de la voirie routière",
]
